### ISSUE TITLE
Sync push state from push target

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#289]
In cases, when you need to reference models already available in push target or simply update push state from push target, then you should be able to do something like this:

    $ spinta push sdsa.csv -o client@put.data.gov.lt --sync

`--sync` flag will update push sync state stored in `{data_path}/push/{remote}.db` and identifiers, stored on `{data_path}/keymap.db` file. Once this is done, you can push data and resolve references from push state.

When updating state from push target, we need to update two things:

- keymap data, to associate external identifiers with local identifiers.
- push state, with checksums from target data source, if checksums do not match or object does not exist on target but exist on push state, then push state should be updated to match state on target.

Even if `--sync` flag is not given, we should still automatically sync identifiers in keymap database for external models, before any push operation. For this it is probably a good idea to utilize changes api and for this, we need to store last change seen by sync.

We should automatically enable `--sync` for first the first time, when `spinta push` is run, after upgrade with this feature, because of previous bugs, some dataset might be in an inconsistent state.

| command | 1 | 2 | 3 |
| --- | --- | --- | --- |
| `spinta push` |  no sync | incremental sync | no sync |
| `spinta push --sync` | full sync | full sync | no sync |

1. models with source
2. models without source referenced by models with source
3. models without source **not referenced** by models with source

# Tasks

- [x] Sync keymap
- [x] Sync push sate

# Related

- https://github.com/atviriduomenys/spinta/issues/208
- https://github.com/atviriduomenys/spinta/issues/149

# Depends on

- https://github.com/atviriduomenys/spinta/issues/311
- https://github.com/atviriduomenys/spinta/issues/394
- https://github.com/atviriduomenys/spinta/issues/345

**Comment by sirex** [comment]
This task is split into two separate pull requests, one syncs only keymap and the other syncs push state.

**Comment by JuliusLADP** [comment]
Mantai, reikia atskirti  'Sync push sate' dalį detalizuojant užduotį

**Comment by JustinasKen** [comment]
`push state` sinchronizacija buvo įgyvendinta https://github.com/atviriduomenys/prieziura/issues/98 užduotyje.
