### ISSUE TITLE
Prettier representation of large geometry objects

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#298]
Use a prettier representation for large geometry objects, like polygons or linestrings, maybe just show centroid point. Example with a bad looking tables:

https://get.data.gov.lt/datasets/gov/giscentras/grpk/VietovardisPlotas

Also fix link to OSM, by converting coordinates to WGS if needed.

**Comment by Gediminas-msc** [comment]
Geometric WKT strings like Polygons and Linestrings will be listed as a geomery type value.
