### ISSUE TITLE
Ūkio subjektų teisinių formų klasifikatorius

### ISSUE THREAD

**Issue by ZymanteM** [atviriduomenys/spinta#321]
Hello,

Would it be possible to add one additional column where we can able to see "Teisinės formos kodas" ( Page 9 in https://data.gov.lt/dataset/1958/download/10676/Instituc-sekt-priskyrimo-tvarkos_aprasas-2021.pdf )

Thank you!

**Comment by sirex** [comment]
Requests to add new data should go to https://data.gov.lt/dataset/statistinis-ukio-subjektu-registras, this repository is for bug related to data publishing service itself.

![image](https://user-images.githubusercontent.com/297583/201319865-2ed1b779-4946-4ff3-b840-325ee51431fa.png)

Press on „Teikti poreikį duomenų rinkinio keitimui“.

**Comment by ZymanteM** [comment]
@sirex , I see my request to add data was completed (https://data.gov.lt/requests/0dc953ac-8bf1-45c6-9762-7606526e39e1) However, the link to reach the data is not working. Can you please advise? Thank you!

**Comment by sirex** [comment]
It seems, that dataset was taken down and a new one was created:

https://data.gov.lt/dataset/juridiniu-asmenu-ekonomines-veiklos-rusys-ir-instituciniai-sektoriai

If not, here is a full list of datasets published by this organization:

https://data.gov.lt/datasets?q=&organization_id=78

And you can contact any organization via this form (registration required):

https://data.gov.lt/requests/new

**Comment by ZymanteM** [comment]
@sirex , has the data structure been changed?
Previously, "ekonomine veikla" was an EVRK number and "sektorius" was ESA number.
![image](https://user-images.githubusercontent.com/114067965/213456931-39b87357-582d-480c-8b6f-e135a0646d0a.png)
![image](https://user-images.githubusercontent.com/114067965/213456977-43626c0f-0cd8-4154-8c7f-2d7e43b4552d.png)

**Comment by sirex** [comment]
You can find change history to the structure here: https://github.com/atviriduomenys/manifest/blob/master/datasets/gov/lsd/cl/ja_asmenys.csv

**Comment by ZymanteM** [comment]
Hello, I checked the given link, but I don't see any change related to this issue. 
From the user's point of view, the ESA and EVRK codes are widely used in reporting.
When we have code ID instead of the true code, we cannot understand what veikla._id and sektorius._ID are without a key table, which we do not have either.

Previously "veikla.ID" was called "ekonomine_veikla", and the value was the code, not ID. 

Maybe it would be possible to return it to the way it was?

Thank you for your time!

![image](https://user-images.githubusercontent.com/114067965/215025333-8f5699dd-78c4-44cb-8198-fb4a5d0d8a18.png)

**Comment by sirex** [comment]
Data in get.data.gov.lt are stored in a normalized way, data of each entity are stored in separate tables. get.data.gov.lt allows to join tables, see the documentation:

https://atviriduomenys.readthedocs.io/api/index.html#jungimas

And here is the example with joined data:

https://get.data.gov.lt/datasets/gov/lsd/cl/ja_asmenys/JuridinisAsmuo?select(kodas,pavadinimas,veikla.kodas,sektorius.kodas)

Here I used following query:

    select(kodas,pavadinimas,veikla.kodas,sektorius.kodas)

You can get whatever you want.

**Comment by ZymanteM** [comment]
Thank you for sharing!
