### ISSUE TITLE
Add support for base metadata in DSA

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#325]
Context: https://github.com/atviriduomenys/spinta/issues/205

Simply allow base type in manifest tables. See tests:

https://github.com/atviriduomenys/spinta/blob/master/tests/manifests/test_tabular.py

Example:

    d | r | b | m | property     | type    | ref     | source 
    example                      |         |         |
      |   |   | Location         |         | id      |
      |   |   |   | id           | integer |         |
      |   |   |   | name@lt      | text    |         |
      |   |   |   | population   | integer |         |
      |   | Location             |         | name@lt |
      |   |   | City             |         | id      | CITY
      |   |   |   | id           | integer |         | ID
      |   |   |   | name@lt      |         |         | NAME
      |   |   |   | population   |         |         | POPULATION

https://github.com/atviriduomenys/spinta/blob/master/spinta/manifests/tabular/helpers.py

### Documentation

- https://atviriduomenys.readthedocs.io/dsa/dimensijos.html#modelio-baze

**Comment by Gediminas-msc** [comment]
Can you make a hint where to find the location to correct data['type'] for the error  "Unknown 'text' type of 'name@lt' property"? Detailed explanation below:

tests/manifests/test_tabular.py:229 (test_base)
tests/manifests/test_tabular.py:231: in test_base
    check(tmpdir, rc, '''
tests/manifests/test_tabular.py:10: in check
    manifest = load_manifest(rc, tmpdir / 'manifest.csv')
spinta/testing/manifest.py:69: in load_manifest
    context = load_manifest_get_context(rc, manifest, **kwargs)
spinta/testing/manifest.py:59: in load_manifest_get_context
    commands.load(context, store.manifest, load_internal=load_internal)
.venv/lib/python3.10/site-packages/multipledispatch/dispatcher.py:278: in __call__
    return func(*args, **kwargs)
spinta/manifests/yaml/commands/load.py:108: in load
    commands.load(
.venv/lib/python3.10/site-packages/multipledispatch/dispatcher.py:278: in __call__
    return func(*args, **kwargs)
spinta/manifests/tabular/commands/load.py:58: in load
    load_manifest_nodes(context, into, schemas, source=manifest)
spinta/manifests/helpers.py:134: in load_manifest_nodes
    node = _load_manifest_node(context, config, manifest, source, eid, schema)
spinta/manifests/helpers.py:195: in _load_manifest_node
    commands.load(context, node, data, manifest, source=source)
.venv/lib/python3.10/site-packages/multipledispatch/dispatcher.py:278: in __call__
    return func(*args, **kwargs)
spinta/types/model.py:83: in load
    load_model_properties(context, model, Property, data.get('properties'))
spinta/nodes.py:218: in load_model_properties
    prop = commands.load(context, prop, params, model.manifest)
.venv/lib/python3.10/site-packages/multipledispatch/dispatcher.py:278: in __call__
    return func(*args, **kwargs)
spinta/types/model.py:219: in load
    prop.dtype = get_node(
spinta/nodes.py:103: in get_node
    raise exceptions.InvalidManifestFile(
E   spinta.exceptions.InvalidManifestFile: Error while parsing '3' manifest entry: Unknown 'text' type of 'name@lt' property in 'example/City' model.
E     Context:
E       component: spinta.components.Property
E       manifest: default
E       schema: 3
E       model: example/City
E       entity: 
E       property: name@lt
E       attribute: 
E       eid: 3
E       error: Unknown 'text' type of 'name@lt' property in 'example/City' model.

**Comment by Gediminas-msc** [comment]
'''
    d | r | b | m | property     | type    | ref
    example                      |         |
      |   |   | City             |         |
      |   |   |   | name         | string  |
      |   |   |   | country      | string  |
      |   | City                 |         | 
      |   |   | CityDemographics |         |
      |   |   |   | name         |         |
      |   |   |   | population   | integer |
    '''

**Comment by Gediminas-msc** [comment]
'''
Type is not given for 'name' property in 'example/CityDemographics' model.
'''
https://github.com/atviriduomenys/spinta/blob/8acfd19f5d2ace9056b757bac1aa977ff40216c8/spinta/manifests/tabular/helpers.py#L472

How to get relative model property (in this case name) type when the base is defined?
