### ISSUE TITLE
Wrong longitude and latitude when opening station location

### ISSUE THREAD

**Issue by Jurkis** [atviriduomenys/spinta#334]
1. Go to https://get.data.gov.lt/datasets/gov/lhmt/klimatologija/MeteorologineAikstele.
2. Click on POINT URL in 'koord' column to open openstreet.com URL with coordinates.

EXPECTED RESULT:  coordinates https://www.openstreetmap.org/?mlat=**56.19320**&mlon=**24.77420**#map=19/**56.19320**/**24.77420** in Lithuania are opened.
ACTUAL RESULT: coordinates in other country https://www.openstreetmap.org/?mlat=**24.774184**&mlon=**56.193191**#map=19/**24.77418**/**56.19319** than Lithuania are opened.

**Comment by marpetr** [comment]
The error is in the data itself. This dataset should be reuploaded with lat and lon coordinates swapped.

**Comment by sirex** [comment]
Gali būti, kad suapiniota yra mūsų pusėje, nes [WGS 84](https://epsg.io/4326) WKT aprašymas sako:

```
       AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
```

Tuo tarpu mūsų pusėje padaryta taip:

https://github.com/atviriduomenys/spinta/blob/ccc7ab12178db7abb1078809090779fc776d8904/spinta/backends/postgresql/types/geometry/helpers.py#L32-L35

Tai reiškia, kad duomenys paduodami teisingai, tačiau atvaizduojami klaidingai.

Todėl, reikėtų

- [ ] [dokumentacijoje](https://atviriduomenys.readthedocs.io/dsa/duomenu-tipai.html#erdviniai-duomenys) patikslinti, argumentų eiliškumą,
- [ ] peržiūrėti kitus `geometry` panaudojimo atvejus, jei jie rodomi teisingai, tada informuoti, kad duomenys rašomi klaidingai,
- [ ] padaryti duomenų migraciją ir pataisyti visas vietas, kur duomenys buvo rašomi klaidingai, pirmiausia susitarus, kad rašymas bus pataisytas
- [ ] galiausiai pataisyti kodą, kad teisingai formuotų osm nuorodas.

**Comment by marpetr** [comment]
If we decide on `POINT(lat lon)` convention, then all we need to fix is swap lon & lat in https://github.com/atviriduomenys/spinta/blob/ccc7ab12178db7abb1078809090779fc776d8904/spinta/backends/postgresql/types/geometry/helpers.py#L33. In this line, `centroid.x` actually refers to latitude and `centroid.y` refers to longitude.
Also need to verify whether `always_xy=True` is necessary on line 28.

**Comment by sirex** [comment]
`POINT(lat lon)` is in the WGS 84 specification. And yes, we need to swap it in the code, because currently it is done incorrectly.

What I'm afraid of, is that data providers might pass data incorrectly, because previously we swapped lat lon to make it work correctly with data, but it turns out, that data itself was provided incorrectly. And currently we have more than 30 data providers, but not all of them use `geometry` type.

@aurjas will look into this.
