### ISSUE TITLE
Delete action returns no body

### ISSUE THREAD

**Issue by julijonas** [atviriduomenys/spinta#416]
Noticed that delete action returns 204 No Content, while docs say that it should return 200 with meta fields in its body.

```
curl -XDELETE https://put-test.data.gov.lt/datasets/gov/a/b/c/d -H "Authorization: Bearer $TOKEN" -v                                                        
...
< HTTP/1.1 204 No Content
...
```

https://atviriduomenys.readthedocs.io/api/index.html#delete

**Comment by sirex** [comment]
Thanks, for reporting, there was an error in documentation, fixed the documentation.
