### ISSUE TITLE
Error on spinta push delete operation with dependent objects

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#458]
`spinta push` tries to delete objects in an incorrect order, ending in foreign key constraint error.

https://github.com/atviriduomenys/spinta/blob/65a4e783241be14cffabd48d87f96e6cedb90aa2/spinta/cli/push.py#L973

In theory, we should delete models in reversed order.

**Comment by justinas55** [comment]
Hello,

In our case this does not fix the problem, as I understand there seems to be some key/ID mismatch or error in detecting deleted rows which in the end are not detected by `_iter_deleted_rows` , but detected by `_get_rows_with_errors` (which checks HTTP API) detects them as deleted with error, but in that code section there is no 'reverse' applied to models and results in the same foreign key constraint error.

It is probably a two-fold problem first one being deleted rows not detected in the first place, but this foreign constraint issue should also be fixed for 'push rows' added by `_iter_rows_with_errors` .

**Workaround/Possible fix.** Adding same `models = reversed(models)` before this line https://github.com/atviriduomenys/spinta/pull/471/files#diff-b71773faa6459532d8c8bf3652029be1e2d7cd8c5d744e0fbc0b5b3bc60acacdR1084 seems to help, but I haven't verified if there are other cases that this would break.

Would appreciate any feedback on this, as this broke integration for my client after some rows were deleted, and I would like to have a proper fix/solution that wouldn't break on updates.

**Comment by sirex** [comment]
Thanks for the feedback, we will look into it.

**Comment by sirex** [comment]
This might be fixed with:

- https://github.com/atviriduomenys/spinta/issues/366

**Comment by adp-atea** [comment]
There was an issue with with deleted row detection, it was using error rows instead of deleted.
This is fixed in https://github.com/atviriduomenys/spinta/pull/559 PR
