### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#472]
```python
Traceback (most recent call last):
  File "spinta/cli/push.py", line 428, in _get_model_row
    rows = tqdm.tqdm(rows, 'PUSH', ascii=True, total=sum(counts.values()))
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'.
```

This error comes from here:

https://github.com/atviriduomenys/spinta/blob/4adc3610d3e9911b20fc53a23d0482b12f891aac/spinta/cli/push.py#L429

And I think it is in `sum(counts.values())`.

`counts` comes from here:

https://github.com/atviriduomenys/spinta/blob/4adc3610d3e9911b20fc53a23d0482b12f891aac/spinta/cli/push.py#L409-L419

And here is `count_rows` function:

https://github.com/atviriduomenys/spinta/blob/4adc3610d3e9911b20fc53a23d0482b12f891aac/spinta/cli/helpers/data.py#L40-L65

It looks, that `None` is coming from `_get_row_count(context, model)`:

https://github.com/atviriduomenys/spinta/blob/4adc3610d3e9911b20fc53a23d0482b12f891aac/spinta/cli/helpers/data.py#L30-L37

It looks, that sql backend returns NULL for `count()` function:

https://github.com/atviriduomenys/spinta/blob/4adc3610d3e9911b20fc53a23d0482b12f891aac/spinta/datasets/backends/sql/commands/query.py#L524-L525

Check if `SELECT COUNT()` can really return NULL, if yes, then coalesce value to be `0`.

Also, add check when returning results if `count()` is `NULL`, then raise an error explaining, what model returned it.

**Comment by adp-atea** [comment]
Could this be database problem ? To me it looks that using postgres is wrong, for example expression like 
select count() will not work. However it seems that returns select count()


![Image](https://github.com/atviriduomenys/spinta/assets/107176624/8eeff552-23ec-4333-9c6a-c8abfd9fecd5)

And after getall command breaks down.

Unless model is not right for this situation.

**Comment by sirex** [comment]
It looks, that issue appears when a model does not have a source. Could you test that?

**Comment by adp-atea** [comment]
It raises error, but its different.


![Image](https://github.com/atviriduomenys/spinta/assets/107176624/6f15666b-31e5-4a1f-8aa3-960a319fbb95)

For example, I`m using model like this


[manifest.csv](https://github.com/atviriduomenys/spinta/files/11755144/manifest.csv)

**Comment by sirex** [comment]
I con't reproduce this either, so I'm closing this issue for now.
