### ISSUE TITLE
Nepavyksta atsisiųsti csv failo

### ISSUE THREAD

**Issue by Skirtum** [atviriduomenys/spinta#488]
Laba diena, 

Bandau atsisiųsti šią laikmeną: https://atviriduomenys.vrk.lt/datasets/gov/vrk/ReitingoEilutes csv formatu. Pastebėjau, kad bandant atsisiųsti duomenis kiekviena iteracija atsisiunčia skirtingas kiekis duomenų. 

Bandau susitikrinti su VRK.lt (pvz. kiek dalyvavo rinkėjų "rink_turo_pavad" = "2023 m. kovo 5 d. savivaldybių tarybų ir merų rinkimai (I turas)") ir matau, kad duomenų mažiau nei skelbiama vrk.lt svetainėje. Šiuose rinkimuose anot vrk dalyvavo: 1125658  (https://www.vrk.lt/savivaldybiu-tarybu-ir-meru-2023/rezultatai?srcUrl=/rinkimai/1304/1/1922/rezultatai/lt/rezultataiSavTarNariaiMeraiSavivaldybese.html) rinkėjų. Tačiau atsisiuntęs failą ir išsifiltravęs pagal tą laukelį randu tik 596472 eilutes.

Mano turimas atsisiųsto failo dydis: 683MB (maksimalus kiekis eilučių, kuriuos pavyko atsisiųsti).

Mėginau su FireFox'u ir su Chrome.

**Comment by sirex** [comment]
@aurjas čia matyt reikia susisiekti su VRK. Bet, klaida gali būti susijusi su:

- https://github.com/atviriduomenys/spinta/issues/366

Dar galima būtu siustis gabalais, bet irgi yra kita klaida:

- https://github.com/atviriduomenys/spinta/issues/490

**Comment by sirex** [comment]
Išspręsta padidinus timeout serveryje.
