### ISSUE TITLE
Error on _id>"UUID" query

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#490]
For example:

https://atviriduomenys.vrk.lt/datasets/gov/vrk/ReitingoEilutes?_id>"697dacf1-3e56-40ba-b9fb-f99b5c670931"&sort(_id)

Returns:

`InvalidValue` error.

**Comment by adp-atea** [comment]
Didin`t add 'eq' operation, since request with this was already working, also not added startswith and contains, they are not supported
