### ISSUE TITLE
Dėl mokesčių mokėtojų registre fiksuotų juridinių asmenų duomenų

### ISSUE THREAD

**Issue by RytisWedeliver** [atviriduomenys/spinta#499]
Sveiki, norėdami susirasti informaciją apie juridinius asmenis ir jų vykdomą ekonominę veiklą (EVRK kodus) susidūrėme su problema, kad:
1. Šioje svetainėje šie duomenys neatsidaro: https://open-data-ls-osp-sdg.hub.arcgis.com/
2. Šioje svetainėje įkeltas dokumentas stulpelyje apie ekonominę veiklą atvaizduoja nuorodą, bet ne priskirtą įmonei EVRK kodą: https://get.data.gov.lt/datasets/gov/vmi/mm_registras/:ns
Taigi, klausimas, kaip ir kur galėtume rasti informaciją apie registruotus juridinius asmenis ir jų vykdomą ekonominę veiklą pagal EVRK kodus.

Ačiū!

**Comment by Faustasm** [comment]
Sveiki, kaip kalbėjom paštu, problema, kad atsidarius https://get.data.gov.lt/datasets/gov/vmi/mm_registras/MokesciuMoketojas EVRK duomenys yra pasiekiami tik paspaudus ant id. Jums reikia padaryti join tarp Mokesčių mokėtojo lentelės ir EVRK. Pavyzdžiui:
https://get.data.gov.lt/datasets/gov/vmi/mm_registras/MokesciuMoketojas?select(_id, pavadinimas, ekonomine_veikla.kodas, ekonomine_veikla._id). Po select skliaustų pasirinkit, kas reikalinga. Kad matytumet visus joino rezultatus vietoj 100, atsisiųskit duomenis json, csv ar kitu formatu.
