### ISSUE TITLE
Dėl Individualios veiklos duomenų reiškmių

### ISSUE THREAD

**Issue by NerijusC** [atviriduomenys/spinta#522]
Laba diena,

analizuoju lentelę "https://get.data.gov.lt/datasets/gov/vmi/veiklos/IndividualiVeikla" ir norėčiau žinoti, apie kuriuos asmenis čia pateikta informacija: ar čia apie visus asmenis, kurie kažkada vykdė individualią veiklą (pagal pažymą), ar tik dalį?

Taip pat, kuo skiriasi "pradzia", "veiklos_pradzia" ir "vietoje_pradzia"? Kodėl kai kada nuo "pradzia" iki "pabaiga" laikotarpis nepersidengia su "veiklos_pradzia" ir "veiklos_pabaiga" laikotarpiu?

Atsiprašau, jei šis laiškas skirtas ne jums, bet prašyčiau, kad persiųstumėt arba nurodytumėt, kam reikėtų man persiųsti.

Ačiū
Nerijus

**Comment by sirex** [comment]
Klausimą apie duomenų turinį galima pateikti atvirų duomenų portale, prie konkretaus duomenų rinkinio: https://data.gov.lt/datasets/1912/
