### ISSUE TITLE
Do not add global elements without references.

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#611]
If element is defined globally in XSD file and are references from other elements, do not create separate DSA entries, for global elements.

For example if we have:

```xml

<element name="a">
  <complexType>
    <attribute ref="b" />
  </complexType>
</element>
<element name="b" />
```

Since `b` is reference by `a`, and `b` is not referenced by any other element we don't need to add a separate entry in DSA for `b`.

**Comment by karina-klinkeviciute** [comment]
fixed as part of #160
