### ISSUE TITLE
Error in composite ref with literal in prepare

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#670]
```
d | r | b | m | property | type    | ref                       | source       | prepare
example                  |         |                           |              |
  |   |   | Translation  |         | id                        | translations |
  |   |   |   | id       | integer |                           | id           |
  |   |   |   | lang     | string  |                           | lang         |
  |   |   |   | name     | string  |                           | name         |
  |   |   |   | city_id  | integer |                           | city_id      |
  |   |   |   |          |         |                           |              |
  |   |   | City         |         | id                        | cities       |
  |   |   |   | id       | integer |                           | id           |
  |   |   |   | en       | ref     | Translation[city_id,lang] |              | id, "en"
  |   |   |   | name_en  | string  |                           |              | en.name
  |   |   |   | lt       | ref     | Translation[city_id,lang] |              | id, "lt"
  |   |   |   | name_lt  | string  |                           |              | lt.name
```

This should generate following query:

```sql
SELECT
  cities.id
  translations.name
FROM cities
LEFT JOIN translations ON (
  translations.city_id = cities.id AND
  translations.lang = "en"
)
```

### Related

- https://github.com/atviriduomenys/spinta/issues/409

**Comment by JustinasKen** [comment]
Reikia komentaro ir patikslinimo, kaip atrodytų `backend` stulpeliai tokiu atvėju, kadnagi viskas išskaičiuojama.

Kaip atrodytu `get` response
`post`, `put`, `patch` requests ir jų response.

By default, jei `ref.level >= 4` yra sukuriamas `ref._id` stulpelis ir visos užklausos veikia pagal tai.

Patikrinau su `external `sql` `backend`, yra padarytas panašus funkcionalumas, bet kadangi, toks dalykas kaip `_id` ten neegzistuoja, `QueryBuilder` veikia šiek tiek kitaip ir ten galima paprasčiau daryti tokias užklausas. `PgQueryBuilder` viską daro per `_id` stulpelį, kadangi assumina, kad jis visada egzistuoja.

Tokiu atvėju reiktu panaikinti prielaidą, kad visi `internal` `backend` `ref level >= 4` turi `_id`, pagal kurį darom joins, kas skamba kaip gana drastiškas pakeitimas ?

**Comment by sirex** [comment]
Kol kas aktualu tik external sql backendui.
