### ISSUE TITLE
Dora

### ISSUE THREAD

**Issue by Dora962** [atviriduomenys/spinta#712]
Laba diena!

Ar yra galimybė peržiūrėti paskesnes duomenų sąrašo eilutes (daugiau nei 100)?
![sąrašo pvz](https://github.com/user-attachments/assets/61b32f47-aba7-42b0-ad89-7da252e2c2dd)

Dėkoju

**Comment by sirex** [comment]
Galima atsisiųsti visus duomenis pasirinktu formatu, HTML formatu, nuo 0.1.61 versijos (#529) atsirado "next page" nuoroda, kuri leidžia pereiti į sekantį puslapį.

Alternatyviai, galima adreso juostoje nurodyti `?limit(200)`, kad pamatyti 200 objektų ([dokumentacija apie limit()](https://ivpk.github.io/uapi/#section/Query/Limit)).

**Comment by Dora962** [comment]
Laba diena!

 

Dėkui už naudingus patarimus.

 

Sėkmės Jums! 

 

Pagarbiai

Dora Petkauskaitė

atstovė spaudai

 



 

www.antstoliurumai.lt

Konstitucijos pr. 15

LT-09319 Vilnius

mob. tel. +370  670 199 22

 ***@***.***> ***@***.***

 

FB Lietuvos antstoliai

https://www.facebook.com/lietuvosantstoliai
