### ISSUE TITLE
InternalSqlManifest blogai nuskaito įrašus

### ISSUE THREAD

**Issue by JustinasKen** [atviriduomenys/spinta#715]
#113 užduotis pridėjo `InternalSQLManifest` manifest tipą, kuris yra `TabularManifest` konversija į `SQL` duomenų bazę. Kadangi veikia panašiu principu kaip `TabularManifest`, eilučių skaitymui yra svarbus eiliškumas. Tam užtikrinti yra naudojamas `index` stulpelis. Yra keletas vietų, kai skaitant duomenis nerūšiuojama pagal `index`, ko pasekoje gauname klaidas, kad negalime pasiekti tam tikrų duomenų.

Edit (2024-07-29):
https://github.com/atviriduomenys/spinta/issues/715#issuecomment-2255010340
reiktų patikrinti `limit(1)` vietas ir kur reikia įdėti `one()`.

 ## Užduotys
- [x] Prie eilučių užklausų, kurios neturi `limit(1)`, jei nėra pridėtas `order_by(index)`, pridėti rūšiavimą.
- [x] Paimti pilną `manifest` struktūrą (iš github) ir paleisti `spinta copy` komandą, konvertuojant į sql variantą.
- [x] Patikrinti `limit(1)` vietas ir kur reikia pakeisti į `one()`.

## Susiję

- #113 
- https://github.com/atviriduomenys/katalogas/issues/346

**Comment by sirex** [comment]
Įtarimą kelia `limit(1)`, jei vykdoma užklausa, kurios metu, tikimasi gauti vieną rezultatą reikėtu naudoti [one()](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.CursorResult.one), o ne `limit(1)`.

**Comment by JustinasKen** [comment]
Galiu prie to pačio peržvelgti `limit(1)` vietas, yra keleta vietų, kur yra daromas `or` (`has_namespace` funkcija), kur reikia žinoti ar yra nors vienas įrašas, kur prasideda tokiu `namespace`, bet yra ir kitų vietų, kur teoriškai turėtų būti tik vienas įrašas.

**Comment by JuliusLADP** [comment]
Mantai, jeigu negali operatyviai pratestuoti, tai tuomet permesk į Diegimas
