### ISSUE TITLE
Spinta shuts down after PostgreSQL becomes unavailable.

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#730]
PostgreSQL logs:

```
FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

Gunicorn logs:

```
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at:
Waiting for application shutdown.
Application shutdown complete.
Finished server process [21765]
Worker exiting (pid: 21765)
Shutting down
Error while closing socket [Errno 9] Bad file descriptor
Waiting for application shutdown.
Application shutdown complete.
Finished server process [22514]
Worker exiting (pid: 22514)
Shutting down
Error while closing socket [Errno 9] Bad file descriptor
Waiting for application shutdown.
Finished server process [21873]
Worker exiting (pid: 21873)
Shutting down: Master
Reason: Worker failed to boot.
```

Systemd logs:

```
spinta.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
spinta.service: Failed with result 'exit-code'.
```

After this Spinta service shuts down.

It looks, that PostgreSQL becomse busy and Spinta shuts down.

Even if PostgreSQL become unavailable, Spinta should not shut down, but keep retrying connections.

**Comment by JuliusLADP** [comment]
Jeigu Mantas operatyviai neatsakys, aptartus su Donatu diegti naujinimą

**Comment by JuliusLADP** [comment]
Įgyvendinti Manto rekomendaciją: Spinta palaiko daug backendų, vienu metu, jei vienas iš backendų nustojo veikti, tai Spinta dėl to neturėtu išsijungti.

ir tikriausiai rodyti pranešimą kurie backendai neveikia?

**Comment by JustinasKen** [comment]
Pavyko atkartoti, kai bandome pajungti `spinta` serverį ir duomenų bazės yra nepajungta.

tai vyksta `wait` funkcijoje, kai pasibaigia laukimo limitas:
https://github.com/atviriduomenys/spinta/blob/46b3b0749a1ba975384df05476c1baee8a2cca96/spinta/backends/postgresql/commands/wait.py#L17-L18

tai reiškiasi, kad tai nėra bug, o feature.

Kas gaunasi, kad jei dėl bet kokios priežasties nulūžta `spinta` procesas ir bandome pakelti iš naujo, o tuo metu duomenų bazė yra nepasiekiama, `spinta` nepasileidžia, tai yra, error atsiranda bandant paleisti `spinta`, o ne spintos veikimo eigoje.

Įdomu būtų sužinoti, kodėl buvo padarytas error `raise`, o ne `return False`.

Yra keli galimi sprendimo būdai:

1. Padidinti `wait` time https://github.com/atviriduomenys/spinta/blob/be44d582b69f5428c07e4fa28b0c2634b8ec2295/spinta/config.py#L177 dalyje.
2. Padaryti `infinite` `wait`, pridedant galimybę supportinti `'wait': 0` config reikšmę.
3. Panaikinti error `raise`, tik reiktų įsitikinti kokios bus pasekmės (galima pridėti `config` reikšmę, kuri leistu valdyti ar `wait` rerases error, ar ne).

**Comment by sirex** [comment]
Wait buvo padarytas būtent dėl tos priežasties, kad palauktų, kol užsikraus backendas ir kad neišsijungtu Spinta užsikrovimo metu.

Matyt geriausias pirmas variantas, padidinti `wait` laiką, jei dabartinio default neužtenka.

Jei panaikinti `raise`, tada papildomai reikia padaryti `Backend` pusėje funkcionalumą, kuris leistu žinoti kitoms dalims, kad backendas yra nepasiekiamas ir kad visi, kurie kreipiasi į neveikiantį backendą, atitinkamai apdorotu tokio pobūdžio klaidą ir tarkim http request atveju, grąžintu klaidą, `BackendOffline` ar panašiai.

Paprastesnis variantas, matyt tiesiog padidinti wait laiką?
