### ISSUE TITLE
Greitaveikos fiksavimas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#732]
Po Saugyklos atnaujinimo iš 0.1.55 į 0.1.67 versiją, pastebimas ženklus sulėtėjimas.

Duomenų skaitymo užklausos, kurios anksčiau truko 7 minutes, po atnaujinimo trunka 1 valandą ir ilgiau, tai yra beveik 10x sulėtėjimas.

Kad ateityje išvengti tokio stipraus greitaveikos sulėtėjimo, reikia kiekvienai versijai fiksuoti esminių užklausų laiką, kad būtų galimybė palyginti, koks padarytas poveikis greitaiveikai, atsiradus naujiems pakeitimams.

Reikėtu fiksuoti visų veiksmų su duomenimis greitaveikos rodiklius, getone, getall, search, insert, ...

Testai turėtu būti leidžiami ant skirtingų Spintos versijų, lygiai tokiomis pačiomis sąlygomis, su duomenų kiekiais, kurie turi bent 1 milijoną ar daugiau objektų.

Tokį greitaveikos testą reikėtu paleisti kiekvieną kartą prieš diegimą, palyginant su ankstesne Spinta versija. Jei greitaveika krenta daugiau kaip 5%, reikėtu stabdyti diegimą ir registruoti klaidą, dėl nukritusios greitaveikos ir aiškintis priežastis kodėl toks sulėtėjimas.

**Comment by JuliusLADP** [comment]
Testavimas turi būti atliekamas ATEA testavimo metu testinėje aplinkoje prieš diegiant į gamybinę aplinką

**Comment by JustinasKen** [comment]
Atlikau kelis greičio išbandymus tarp `0.1.55` ir `0.1.68` versijos.

Duomenų struktūra:
id | d | r | b | m | property | type    | ref     | source | prepare | level | access | uri | title | description
   | dataset                  |         |         |        |         |       |        |     |       |
   |                          |         |         |        |         |       |        |     |       |
   |   |   |   | Country      |         | id      |        |         |       | open   |     |       |
   |   |   |   |   | id       | integer |         |        |         |       |        |     |       |
   |   |   |   |   | name     | string  |         |        |         |       |        |     |       |
   |   |   |   |   | code     | string  |         |        |         |       |        |     |       |
   |                          |         |         |        |         |       |        |     |       |
   |   |   |   | City         |         | id      |        |         |       | open   |     |       |
   |   |   |   |   | id       | integer |         |        |         |       |        |     |       |
   |   |   |   |   | name     | string  |         |        |         |       |        |     |       |
   |   |   |   |   | country  | ref     | Country |        |         |       |        |     |       |
   
   Duomenys buvo sugeneruoti tokiu būdu
   ```sql
   INSERT INTO "dataset/Country" (_id, id, name, code)
SELECT uuid_generate_v4(), i, i::text, i::text
FROM generate_series(1, 1000000) as t(i);

INSERT INTO "dataset/City" (_id, id, name, "country._id")
SELECT uuid_generate_v4(), t.id, t.name, t."_id"
FROM "dataset/Country" as t;
   ```
   
   # `0.1.55` versijos rezultatai:
   `GET http://127.0.0.1:8000/dataset/City` - 1M įrašų 46.03s 164.77MB
     `GET http://127.0.0.1:8000/dataset/City` - 500k įrašų 22.88s 82.28MB	
   
   # `0.1.68` versijos (atjungus puslapiavimą) rezultatai:
   `GET http://127.0.0.1:8000/dataset/City?page(disable:true)` - 1M įrašų 1m 19.20s 164.77MB
  `GET http://127.0.0.1:8000/dataset/City?page(disable:true)` - 500k įrašų 40.33s 82.28MB	
  
  Darant užklausas be puslapiavimo smarkiai neįtakojam duomenų bazės RAM panauodojimo, bet CPU panaudojimas yra aukštas, vienas branduolys vos ne visada buvo 100%

Skirtumas tarp versijų yra apie 0.035ms per įrašą (tai atsirado dėl sudėtingesnio įrašų apdorojimo proceso).

Plačiau apie puslapiavimo įtaką užklausų greičiui, serverio CPU ir duomenų bazės RAM papildysiu rytoj.

**Comment by sirex** [comment]
CPU naudojimas:

![chart](https://github.com/user-attachments/assets/3beabba5-5d31-4cea-961d-dcc1defb8e80)

RAM naudojimas:
![chart (1)](https://github.com/user-attachments/assets/3575f138-c0ca-48c5-846f-94e639ce29d9)

0.1.66 versijos diegimas buvo atliktas 2024-07-29.

Panašu, kad išaugo tiek RAM naudojimas, tiek CPU. Reikėtu išsiaiškinti kas tiksliai taip stipriai padidino resursų naudojimą ir pataisyti.

Reikia žiūrėti kokios tiksliai užklausos siunčiamos. Reikia įsitikinti ar sudėti indeksai ant laukų, pagal kuriuos atliekamas rūšiavimas.

Turiu įtarimą, kad daromas rūšiavimas pagal lauką, kuris neturi indekso, ko pasekoje daromas full scan. Tokiu atveju, matyt reikia loginti laukus, pagal kuriuos daromas filtravimas ir rūšiavimas. Jei tam tikri laukai dažnai naudojami filtruojant ar rūšiuojant ir užklausos trunka ilgai, tada reikėtu konfigūracijoje nurodyti, indeksus, susiję su:

https://github.com/atviriduomenys/spinta/issues/599

Žinoma, jei priežastis tikrai tame, tada reikia tam kartui rankiniu būdu sudėti indeksus, laukams, kurie dažnai naudojami filtruose.

Kokie laukai naudojami, galima išsirinkti iš accesslog.

Ateityje, didelėms lentoms gal iš vis reikėtu drausti filtravimą ir rūšiavimą, jei nėra indekso?

**Comment by JustinasKen** [comment]
Lokalaus testavimo rezultatai ant Windows 10, su 1M įrašų, naudojant docker postgresql ir AMD Ryzen 7 5700g 16core CPU

| versija | paramterai | trukmė | docker memory usage | server CPU peak | server CPU avg | 1 Core average |
| ------- | ------------ | -------- | ------------------------ | ------------------ | ----------------- | ---------------- |
| 0.1.55 |  | 45.43s | 2MiB | 8.3% | 8% | 80-100% |
| 0.1.68 | page(disable:true) | 1m 19.20s | 0.3MiB | 9.2% | 7.5% | 80-100% |
| 0.1.68 | page(size:1000) | 2m 55.32s | 300.6MiB | 7.5% | 4.5% | 40-80% |
| 0.1.68 | page(size:2500) | 2m 2.34s | 228.7MiB | 8.3% | 5% | 50-80% |
| 0.1.68 | page(size:5000) | 1m 44.47s | 213.4MiB | 8% | 6.5% | 50-80% |
| 0.1.68 | page(size:7500) | 1m 38.83s | 209.2MiB | 8.5% | 7% | 60-80% |
| 0.1.68 | page(size:10000) | 1m 35.70s | 201.4MiB | 8.2% | 7% | 60-90% |
| 0.1.68 | page(size:12500) | 1m 34.08s | 203MiB | 8.2% | 7% | 70-90% |
| 0.1.68 | page(size:50000) | 1m 30.66s | 102.8MiB | 8.5% | 8% | 80-90% |

**Comment by sirex** [comment]
Buvo nusiskundimai, kad sulėtėjimas yra 10 ir daugiau kartų, turiu įtarimą, kad tai pasireiškia, kai naudojamas rūšiavimas pagal neindeksuotus laukus. T.y. kai nenaudojami parametrai, puslapiavimas vyksta pagal indeksuotą `_id` lauką, tačiau jei rūšiuojama pagal neindekstuotą lauką, tada greitaveika turėtu būti žymiai prastesnė.

Klausimas, kodėl 0.1.55 ir 0.1.68 su page(disable:true) veikia daugiau kaip 2 kartus lėčiau?

**Comment by JustinasKen** [comment]
Puslapiavimo dalis bus tvarkoma #735 užduotyje.

**Comment by JustinasKen** [comment]
Toliau testuojant buvo paleista `getall` `PostgreSql` funkcijos `line_profiler` patikrinimas.
Rezultatas:
```python
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    62                                           @profile
    63                                           def fun_(
    64                                               context: Context,
    65                                               model: Model,
    66                                               backend: PostgreSQL,
    67                                               *,
    68                                               query: Expr = None,
    69                                               default_expand: bool = True,
    70                                               params: QueryParams = None,
    71                                               **kwargs
    72                                           ):
    73         1         16.0     16.0      0.0      assert isinstance(query, (Expr, type(None))), query
    74         1      72709.0  72709.0      0.0      connection = context.get('transaction').connection
    75                                           
    76         1          3.0      3.0      0.0      if default_expand:
    77                                                   if params is None:
    78                                                       params = QueryParams()
    79                                                   params.default_expand = default_expand
    80                                           
    81         1        100.0    100.0      0.0      builder = PgQueryBuilder(context)
    82         1         36.0     36.0      0.0      builder.update(model=model)
    83         1        197.0    197.0      0.0      table = backend.get_table(model)
    84         1        320.0    320.0      0.0      env = builder.init(backend, table, params)
    85         1     278382.0 278382.0      0.2      expr = env.resolve(query)
    86         1         27.0     27.0      0.0      where = env.execute(expr)
    87         1      11271.0  11271.0      0.0      qry = env.build(where)
    88                                           
    89         1        162.0    162.0      0.0      conn = connection.execution_options(stream_results=True)
    90         1    3497599.0    3e+06      2.0      result = conn.execute(qry)
    91                                           
    92    100001   18246915.0    182.5     10.6      for row in result:
    93    100000     241999.0      2.4      0.1          res = {}
    94    100000     214473.0      2.1      0.1          list_keys = []
    95    600000    1941542.0      3.2      1.1          for key, sel in env.selected.items():
    96    500000    1285266.0      2.6      0.8              if key in model.flatprops:
    97    500000    1250309.0      2.5      0.7                  prop = model.flatprops[key]
    98    500000    1211370.0      2.4      0.7                  if prop.list is not None and prop.list.place not in list_keys:
    99                                                               list_keys.append(prop.list.place)
   100    500000   71884978.0    143.8     42.0              val = get_row_value(context, backend, row, sel, False)
   101    500000    1386434.0      2.8      0.8              res[key] = val
   102    100000    1311804.0     13.1      0.8          if env.page.page_.is_enabled:
   103    100000    4844611.0     48.4      2.8              res['_page'] = get_page_values(env, row)
   104                                           
   105    100000     751901.0      7.5      0.4          res['_type'] = model.model_type()
   106                                           
   107    100000   27528934.0    275.3     16.1          res = flat_dicts_to_nested(res, list_keys=list_keys)
   108    100000   35175662.0    351.8     20.5          res = commands.cast_backend_to_python(context, model, backend, res)
   109    100000     200173.0      2.0      0.1          yield res
```

**Comment by JustinasKen** [comment]
`PostgreSQL` `backend` `getall` funkcijos refactorinimas bus atliktas #746 užduotyje.

**Comment by JustinasKen** [comment]
Po sudiegtų #735 ir #746 užduočių, buvo atliktas testavimas testinėje aplinkoje.

Pasirinktas https://github.com/atviriduomenys/manifest/blob/13207c3781234c1659b4613be16790dc8859d42e/datasets/gov/ivpk/adk.csv#L405-L410
`UserVote` modelis.

Buvo supushinta 150k sugeneruotų įrašų ir patikrinta `push`, `getall` ir `getall` be puslapiavimo greitaveika.

Lyginamos versijos: `0.1.67` (prieš greitaveikos pakeitimus) ir `0.1.70` (po greitaveikos pakeitimo)

# Pridėti rezultatus

**Comment by ATEAanalyst** [comment]
Ar užduotį galima bus uždaryti? Ar dar tikimasi kažkokių veiksmų?

**Comment by JuliusLADP** [comment]
Reikia išvados patikslinimo, nes pateikti vienas kitam prieštaraujantys teiginiai dėl puslapiavimo - pagreitėjo ir su puslapiavimu ir be puslapiavimo?:

getall su puslapiavimu pagreitėjo 8.82s arba apie 32%
getall be puslapiavimo pagreitėjo 6.41s arba apie 33%

**Comment by Grigorjeva11** [comment]
@JuliusLADP  Laukiame komentaro, ar reikia imtis papildomu veiksmų, ar galime uždaryti uždavinį.
