### ISSUE TITLE
Pakeisti puslapiavimo konfiguraciją

### ISSUE THREAD

**Issue by JustinasKen** [atviriduomenys/spinta#735]
Atliekant #732 užduoties analizę buvo aptikta, kad su dabartiniais puslapiavimo nustatymais užklausos suletėja apie 55%.
Plačiau apie puslapiavimo rezultatus:
https://github.com/atviriduomenys/spinta/issues/732#issuecomment-2301349133

Reikia Pridėti naują konfiguracijos lauką: `enable_pagination = True`.
Šis laukas nurodys, kokiu režimu (by default) bus paleistos užklausos, jei užklausoje bus nurodytas `page(disable: false)`, o 
`enable_pagination` bus `False`, puslapiavimas vis tiek bus įjungtas.

Pakeisti  `push_page_size` pavadinimą į `default_page_size`, taip pat jis neturėtų būti `None`, o turėtų būti privalomai nurodyta reikšmė. Pradinė reikšmė turi būti `100000`, o ne `1000`

## Užduotys
- [x] `enable_pagination` konfiguracinis laukas.
- [x] `push_page_size` pavadinimą į `default_page_size`.
- [x] Pakeisti `default_page_size` į `100000`.

## Susiję
- #732

**Comment by JuliusLADP** [comment]
Mantai, jeigu negali operatyviai pratestuoti, tai tuomet permesk į Diegimas
