### ISSUE TITLE
Spinta nepriima geometry POINT, epsg:3346

### ISSUE THREAD

**Issue by dovileer** [atviriduomenys/spinta#737]
Paduodant POINT (x, y) nebepriima LKS-94 koordinačių, gaunama tokia klaida:
`ServiceException: CUSTOM_CLIENT (MagritteRestSource:InvalidResponseStatus): {responseCode=400, validCodes=[200, 201, 204], response={"errors":[{"type":"type","code":"CoordinatesOutOfRange","template":"Given coordinates: {given!r} ar not within the {srid!r} available bounds: {bounds} (west, south, east, north).","context":{"component":"spinta.types.geometry.components.Geometry","manifest":"default","schema":"27270","dataset":"datasets/gov/vtpsi/infostatyba","model":"datasets/gov/vtpsi/infostatyba/Statinys","entity":"","property":"taskas_lks","attribute":"","type":"geometry","given":"POINT (6179416.800000000000 320593.300000000000)","srid":"epsg:3346","bounds":"(172763.81342171825, 5972477.980305717, 685350.9526821912, 6268543.171629876)"},"message":"Given coordinates: 'POINT (6179416.800000000000 320593.300000000000)' ar not within the 'epsg:3346' available bounds: (172763.81342171825, 5972477.980305717, 685350.9526821912, 6268543.171629876) (west, south, east, north)."}]}, filename=datasets_gov_vtpsi_infostatyba_Statinys?#2024-08-22T06_23_44.441732906Z}`

Tikrinant tas pačias koordinates, čia atvaizduoja teisingai - https://get.data.gov.lt/_srid/3346/6179416.800000000000/320593.300000000000

Klaida pastebėta skirtinguose rinkiniuose, vienas iš jų https://get.data.gov.lt/datasets/gov/vtpsi/infostatyba/Statinys
stulpelis "taskas_lks" anksčiau priimdavo tokiu pat formatu eksportuojamas koordinates.

Kitas pvz.: 
Kai siunčiama POINT (x,y)
Gaunama klaida – 
`{"errors":[{"type":"type","code":"CoordinatesOutOfRange","template":"Given coordinates: {given!r} ar not within the {srid!r} available bounds: {bounds} (west, south, east, north).","context":{"component":"spinta.types.geometry.components.Geometry","manifest":"default","schema":"25257","dataset":"datasets/gov/vat/fitosanitarijos_postai","model":"datasets/gov/vat/fitosanitarijos_postai/Punktas","entity":"","property":"koord","attribute":"","type":"geometry","given":"POINT (6056945 608793)","srid":"epsg:3346","bounds":"(172763.81342171825, 5972477.980305717, 685350.9526821912, 6268543.171629876)"},"message":"Given coordinates: 'POINT (6056945 608793)' ar not within the 'epsg:3346' available bounds: (172763.81342171825, 5972477.980305717, 685350.9526821912, 6268543.171629876) (west, south, east, north)."}]} `

Siunčiama tokia jsonl užklausa -
`{"_op":"patch","_where":"_id='93061d72-fa9f-4b05-bf8d-1ea5399f555d'","_revision":"c2fdfed4-efe2-47f8-8715-c698b4fbcb38","id":"1281f740305d871","padalinys":"Medininkų pasienio kontrolės punkto fitosanitarijos postas (skyrius)","adresas":"Vilniaus r. sav., Kalvelių k.","koord":"POINT (6056945 608793)"}`

Apkeitus koordinates vietomis POINT (y, x) :
`{"_op":"patch","_where":"_id='93061d72-fa9f-4b05-bf8d-1ea5399f555d'","_revision":"c2fdfed4-efe2-47f8-8715-c698b4fbcb38","id":"1281f740305d871","padalinys":"Medininkų pasienio kontrolės punkto fitosanitarijos postas (skyrius)","adresas":"Vilniaus r. sav., Kalvelių k.","koord":"POINT (608793 6056945)"} `
 
Suveikė, tačiau žemėlapyje atvaizduoja ne Lietuvos teritorijoje.
![image](https://github.com/user-attachments/assets/b1901383-d5d1-492a-963c-7fdc60edc0c0)
![image](https://github.com/user-attachments/assets/c12710c8-352a-459b-9654-d7118f42d923)

### Susiję

- https://github.com/atviriduomenys/spinta/issues/410

**Comment by JuliusLADP** [comment]
Pakartotinis duomenų teikėjų problemos aprašymas:

rinkiniu, kuriame yra LKS94 POINT (stulpelis “taskas_lks”) - https://get.data.gov.lt/datasets/gov/vtpsi/infostatyba/Statinys

1)	Kai siunčiama POINT (6064368.0 577673.0) (kaip suprantu pagal duomenų atvėrimo vadovą taip rekomenduojama), gaunama klaidą ir neįsikelia koordinatės.
Klaida –
ServiceException: CUSTOM_CLIENT (MagritteRestSource:InvalidResponseStatus): {responseCode=400, validCodes=[500, 200], response={"errors":[{"type":"type","code":"CoordinatesOutOfRange","template":"Given coordinates: {given!r} ar not within the {srid!r} available bounds: {bounds} (west, south, east, north).","context":{"component":"spinta.types.geometry.components.Geometry","manifest":"default","schema":"27302","dataset":"datasets/gov/vtpsi/infostatyba","model":"datasets/gov/vtpsi/infostatyba/Statinys","entity":"","property":"taskas_lks","attribute":"","type":"geometry","given":"POINT (6064368.0 577673.0)","srid":"epsg:3346","bounds":"(172763.81342171825, 5972477.980305717, 685350.9526821912, 6268543.171629876)"},"message":"Given coordinates: 'POINT (6064368.0 577673.0)' ar not within the 'epsg:3346' available bounds: (172763.81342171825, 5972477.980305717, 685350.9526821912, 6268543.171629876) (west, south, east, north)."}]}, filename=datasets_gov_vtpsi_infostatyba_Statinys?#2024-09-12T17_45_10.666431295Z}

2)	Tam pačiam rinkiniui apkeitus koordinačių eiliškumą, pavyksta įkelti (stulpelis “taskas_lks”) – 
https://get.data.gov.lt/datasets/gov/vtpsi/infostatyba/Statinys/:changes/-10
 
Čia gaunasi, kad neteisingai atvaizduojamas taskas_lks  žemėlapyje saugykloje (pvz. https://get.data.gov.lt/datasets/gov/vtpsi/infostatyba/Statinys?_revision=%22e7b3d7c9-a0b1-46d1-b5fb-f6619229df6c%22), tačiau bent jau įsikelia duomenys, o pirmu būdu net nepavyksta įkelti. Galbūt galima tiesiog tuo antru būdu kelti?

**Comment by sirex** [comment]
Blogai parašyti testai:

https://github.com/atviriduomenys/spinta/blob/f21a7fb1a44c89b76f1ed1faa1b08a97061e170e/notes/types/geometry.sh#L66

Visur, kur naudojama LKS94, koordinatės turi būti pateiktos šiaurė, rytai eiliškumu:

```wkt
POINT (6237902 432224)
```

Visada LKS, pateikiant WKT formatu, pirma turi eiti didesnis skaičius ~60 tūkstančių km nuo pusiaujo į šiaurę, o antras skaičius mažesnis, nuo 24 laipsniai - 500 km į rytus.

Dabar testuose visur koordinatės surašytos klaidingai.
