### ISSUE TITLE
Pakeisti perspėjimo žinutę

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/spinta#758]
Pakeisti dabartinę perspėjimo žinutę, dėl paklausimo-problemos registravimo vietos get.data.gov.lt:
![Image](https://github.com/user-attachments/assets/75d1e99e-f9dc-4293-8fad-0f42ec70e544)
Pakeisti nuorodos linką į atviriduomenys@vssa.lt

**Comment by JustinasKen** [comment]
Ar tinka tokia žinutė ?

Dėmesio! Atvirų duomenų saugykla šiuo metu yra aktyviai vystoma, todėl galite susidurti su įvairaus pobūdžio sutrikimais, apie kuriuos maloniai prašome pranešti [atviriduomenys@vssa.lt](mailto:atviriduomenys@vssa.lt).

**Comment by JuliusLADP** [comment]
Tinka
