### ISSUE TITLE
Šiaulių rinkinio klaidos duomenų kataloge

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/spinta#759]
išanalizuoti ir jeigu tai nesusiję su DSA, o su Spinta klaida, registruoti kaip bug. 

Jeigu, tai DSA problematika - paaiškinti paklausėjui  Normanas Žemaitis <normanas.zemaitis@sakiai.lt> kaip ją ištaisyti 

Šiaulių savivaldybės duomenų rinkinyje "/datasets/gov/sakiai/gaunami_dokumentai" visos lentelės išskyrus `Dokumentas` ir `GaunamasDokumentas`  meta klaidas:
https://get.data.gov.lt/datasets/gov/sakiai/gaunami_dokumentai/DokumentoFormosTipas. 

![Image](https://github.com/user-attachments/assets/bbff3061-03a1-4ca3-94c5-89b4985138b5)

**Comment by JustinasKen** [comment]
Reikia patikrinti, ar `manifest` yra gerai sutvarkytas / buvo atliktos migracijos.

**Comment by aurjas** [comment]
Klaida metama dėl to, kad nesutampa savybių pavadinimai Struktūros apraše ir duomenų bazėje su tuo kas paduodama į saugyklą. Struktūros apraše ir duomenų bazėje yra savybė pvz. dfrm_pav@lt, o paduodama į saugykla tikriausiai su dfrm_pav pavadinimu. Tas pats su kitais modeliais. Susisiekiau su Normanu. Beje, ne Šiaulių, o Šakių rinkinys.

**Comment by JustinasKen** [comment]
Yra niuansas su `Text` tipu, kad jis by default, jei `manifest` faile turime `property@lang` `String` laukus, konvertuoja `property` į `Text` tipą, kuris yra `property` `json` stulpelis.

tai yra `dfrm_pav@lt = ...` turėtų tapti `dfrm_pav = {'lt': ...}` duomenų bazėje

Plačiau apie `Text` tipą:
https://github.com/atviriduomenys/spinta/issues/204

Gali būti, kad stulpeliai buvo sukurti prieš šitą feature arbo buvo atliekamos migracijos ne pagal naują tipą.

**Comment by aurjas** [comment]
Ištaisyta, klaidų nebemeta.
