### ISSUE TITLE
TEST spinta klaidos

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/spinta#797]
Taigi tęsiu duomenų kėlimo darbus, keliu grafinius duomenis. Naudojame spintos versiją 0.1.67
Bandant sukelti apskritis (spinta push sdsa/ar/sdsa_ar_gra.xlsx -o [rc@put-test.data.gov.lt](mailto:rc@put-test.data.gov.lt) -d datasets/gov/rc/ar/graapskritis --max-errors 1000000) pateikiami warning‘ai „Ambiguities exist in dispatched function select“ ir „warn(warning_text(dispatcher.name, ambiguities), AmbiguityWarning)“ – visiškai neaišku ar tai klaida ar kas. Source yra tik 10 įrašų ir visi jie skirtingi (pridedu vaizdą). Tokios pat klaidos ir su kitais dataset‘ais.
 
![image](https://github.com/user-attachments/assets/a25b7dfc-f429-4828-9afb-6bdededeeb54)

Pabandžiau naują tag‘ą --sync, bet tada gaunu klaidą HTTPError: 500 Server Error: Internal Server Error for url: https://put-test.data.gov.lt/datasets/gov/rc/ar/graapskritis/GraApskritis/:format/json?select(_id,_revision,_page,checksum(),aps_kodas)&sort(_id)&limit(1000)
Bandžiau tą URL įkelti į naršyklę, tai iš karto pateikiama klaida „probably won't serialize to JSON“, išmetus iš URL checksum() pateikiamas rezultatas

**Comment by JustinasKen** [comment]
Warnings nėra errors, jie bus patvarkyti su kitu task.

Svarbiau paskutinis link, ar @LaurynasVenck galėtum pateikti traceback logus atidarant šitą užklausą ?

**Comment by JustinasKen** [comment]
`json` klaida turėtų būti sutvarkyta su:
#832 užduotimi
