### ISSUE TITLE
Klaida keliant ADSA į github

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/spinta#809]
Keliant ADSA į github nepraeina checks dėl tokios klaidos. Panašu, kad susiję su pymongo biblioteka, ar galėtumėte patikrinti kokia klaidos priežastis?
 
 
![image](https://github.com/user-attachments/assets/e85b2304-9bd1-4c8b-beca-004d0f6128d7)

 
Ta pati klaida 2 pull-requestuose:
https://github.com/atviriduomenys/manifest/actions/runs/10938260334/job/30365935306?pr=3629
https://github.com/atviriduomenys/manifest/actions/runs/10938639771/job/30367142657?pr=3630

**Comment by JuliusLADP** [comment]
Justintai, ar apie tai ką nors žinai?

**Comment by JustinasKen** [comment]
taip
https://github.com/atviriduomenys/spinta/issues/806

užduotis tai išspręs ir šiandiena išleisiu naują `spinta` versiją, kuri tai sutvarkys

**Comment by JustinasKen** [comment]
Jei susitvarkė problema su #806 uždarykite užduotį.
