### ISSUE TITLE
Spinta klaidos

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/spinta#821]
Bandant kelti duomenis į TEST spintą gaunama klaida „'message': "Given coordinates: 'POLYGON ((pašalinti taškai))' ar not within the `EPSG: 3346` available bounds: (5972477.980305717, 172763.81342171825, 6268543.171629876, 685350.9526821912) (west, south, east, north).",
'template': 'Given coordinates: {given!r} ar not within the `EPSG: {srid!r}` available bounds: {bounds} (west, south, east, north).'“
Pridedu failą, kuriame viena iš reikšmių, kurios nepraeina validacijos.
Keista situacija dėl to, kad tokia pat reikšmė (kaip pavyzdyje) įkelta į spintą https://put-test.data.gov.lt/datasets/gov/rc/ar/grasavivaldybe/GraSavivaldybe?sav_kodas=32
Naudoju 0.1.67 spintos versiją

**Comment by IngaIVPK** [comment]
[sav_32_irasas.txt](https://github.com/user-attachments/files/17098222/sav_32_irasas.txt)

**Comment by JustinasKen** [comment]
pagal naują versiją, pradėta gerai laikytis rėžių:

Lietuvos koordinatės (3346) yra:

x - northing (latitude)
y - easting (longitude)

https://epsg.io/3346

yra pateiktas bounding box:
172763.81 5972477.98
685350.95 6268543.17
lon             lat

tai yra:
longitude (easting) - nuo 172763.81 iki 685350.95
latitude (northing) - nuo 5972477.98 iki 6268543.17

Lietuvos koordinačių sistema yra latitude, longitude eiliškumu, bet sąraše yra pateikti duomenys:
longitude, latidude (easting, northing).

Atsidarius `epsg` žemėlapį https://epsg.io/map#srs=3346-1283&x=476541.154557&y=6117377.574766&z=7&layer=streets
yra brute forced `x - longitude`, `y - latitude`, todėl galima susimaišyti, bet judinant žemėlapį į šoną, keičiasi x reikšmė (nors Lietuvos sistemoje x reiškia northing), todėl galima pamatyti, kad žemėlapis nesilaiko Lietuvos CRS standarto.
