### ISSUE TITLE
ProgrammingError asmlis/uzsakymai/Uzsakymas

### ISSUE THREAD

**Issue by BenasDe** [atviriduomenys/spinta#850]
Laba diena, 

Reikia atnaujinti duomenis rinkinyje, bet gaunam tokią klaidą :
![image](https://github.com/user-attachments/assets/329e9127-869a-4e35-82d3-777b66239540)

Gal gali užmesti akį kur galėtų būti bėda ? Nebuvo padarytas wipe prieš pridedant į struktūrą šiuos stulpelius:

x_koord_lks
y_koord_lks
platuma_wgs
ilguma_wgs
koord_patik_proc
adreso_tipas 

Po to bandėm wipe task, bet nepadėjo.

Links :
- https://get.data.gov.lt/datasets/gov/asmlis/uzsakymai/Uzsakymas
- https://github.com/atviriduomenys/manifest/blob/3671-trak-r-sav-mokesta-uzsakymai/datasets/gov/asmlis/uzsakymai.csv

**Comment by JuliusLADP** [comment]
pakomentuoti situaciją

**Comment by JustinasKen** [comment]
Turiu nuojauta žiūrint į 2024-10-01 dienos darytus pakeitimus
https://github.com/atviriduomenys/clog/blob/main/servers/get-test.data.gov.lt/2024/10-01_23_aj_manifest.sh
https://github.com/atviriduomenys/clog/blob/main/servers/get.data.gov.lt/2024/10-01_23_aj_manifest.sh

Turbūt buvo praleistas, naujų laukų pridėjimas:
https://github.com/atviriduomenys/manifest/commits/master/datasets/gov/asmlis/uzsakymai.csv

tą pačią dieną buvo 2 commits padaryti, bet nerandu jokio PR, kuris apie tai praneštu.

**Comment by JustinasKen** [comment]
Na problema labiau yra, tai jog kai buvo atnaujintas bendras sistemos `manifest`, jei yra kokie nors egzistuojančių lentų pakeitimai (pridėti / pakeisti columns), juos ranka reikia migruoti. Tai galėjo būti, kad šie laukai tesiog nebuvo pridėti. Priskyriau @JuliusLADP, kad pasiklaustu kokia buvo paskutinio `manifest` migracijos situacija.

**Comment by aurjas** [comment]
Jau pataisyta
