### ISSUE TITLE
Spinta error

### ISSUE THREAD

**Issue by Marius-prog** [atviriduomenys/spinta#889]
https://get.data.gov.lt/datasets/gov/vmi/gyventoju_pajamos/GyventojuPajamos

![Screenshot 2024-10-09 at 13 10 14](https://github.com/user-attachments/assets/31890166-d1cd-49f9-8d91-b80f374b75f9)

**Comment by JustinasKen** [comment]
Ar galite užtikrinti, kad `manifest` yra teisingas ir ar buvo teisingai atliktos migracijos ?

**Comment by aurjas** [comment]
Klaida ištaisyta
