### ISSUE TITLE
Property 'id' not found (JANGIS 437)

### ISSUE THREAD

**Issue by karina-klinkeviciute** [atviriduomenys/spinta#991]
PropertyNotFound: Property 'id' not found.
  Context:
    component: spinta.components.Model
    manifest: default
    schema: Sheet1:87
    model: NaturalPerson
    entity: None
    property: id

![Image](https://github.com/user-attachments/assets/8bc95ebb-8a8d-4e67-9b6f-5c1d9d932bde)

As we can see, `id` actually doesn't exist. When I changed to `person_id`, this error stopped.

**Comment by sirex** [comment]
If `id` is not within `NaturalPerson` properties, then this is an error in manfiesst table.

**Comment by karina-klinkeviciute** [comment]
this is an issue in the data
