### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by karina-klinkeviciute** [atviriduomenys/spinta#993]
legal_status |   | /datasets/gov/rc/jar_ws/klasifikatoriai/Statusas[pavadinimas_i@lt] |  
-- | -- | -- | --

Legal status neturi šaltinio, ir yra išoriškai apibrėžtas modelis:
 ![Image](https://github.com/user-attachments/assets/b5d2255a-2be7-4289-aef2-b9b3d624d757)

Met in Jangis 437

**Comment by sirex** [comment]
Jei nenurodytas `property.type`, tada turi būti nurodytas `model.base`. Klaida DSA faile.
