### ISSUE TITLE
If base is a model in a different dataset, we get an error Model doesn't exist

### ISSUE THREAD

**Issue by karina-klinkeviciute** [atviriduomenys/spinta#996]
![Image](https://github.com/user-attachments/assets/8f28fb34-36cd-4506-b919-49cdf308894c)

From Jangis 437

ModelNotFound: Model 'datasets/gov/rc/ar_ws/text_with_coordinates/Address[id]' not found.
  Context:
    model: datasets/gov/rc/ar_ws/text_with_coordinates/Address[id]

**Comment by sirex** [comment]
All files should be provided as arguments if files depend one from another, for example:

```
spinta check jangis.csv ar.csv
```

If `jangis.csv` depends on `ar.csv`, then `ar.csv` should also be added as command line argument.

**Comment by karina-klinkeviciute** [comment]
Leidžiant su `spinta check` surašius visus failus, ši klaida nemetama. Manau, kad šitą galima uždaryti, taisymas nereikalingas. Ar reikėtų aiškesnį pranešimą pridėti?
