### ISSUE TITLE
If model is from an external dataset, we get an error that it doesn't exist

### ISSUE THREAD

**Issue by karina-klinkeviciute** [atviriduomenys/spinta#998]
![Image](https://github.com/user-attachments/assets/48472a06-9019-4296-8f45-c890e9708b79)

There is a property with a `ref` to an external dataset, but it causes an error:

ModelReferenceNotFound: Model reference 'datasets/gov/rc/ar_ws/text_with_coordinates/Address' not found.
  Context:
    component: spinta.types.datatype.ExternalRef
    manifest: default
    schema: Sheet1:10
    dataset: datasets/gov/rc/jangis_ws/n437_israsas
    resource: resource1
    model: Address
    entity: None
    property: address
    attribute: adresoId/text()
    type: _external_ref
    resource.backend: datasets/gov/rc/jangis_ws/n437_israsas/resource1
    ref: datasets/gov/rc/ar_ws/text_with_coordinates/Address

JANGIS 437

**Comment by sirex** [comment]
Probably same issue as in:

https://github.com/atviriduomenys/spinta/issues/996#issuecomment-2511537132

**Comment by karina-klinkeviciute** [comment]
Taip, tas pats kaip #996 

Leidžiant su spinta check surašius visus failus, ši klaida nemetama. Manau, kad šitą galima uždaryti, taisymas nereikalingas. Ar reikėtų aiškesnį pranešimą pridėti, pavyzdžiui, kad patikrintų ar prideda visus papildomus šaltinius?

**Comment by sirex** [comment]
Buvo sutarta, kad aiškesnio pranešimo nereikia.
